server:
  port: 8080

spring:
  #Mongo Database
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: store
      username: alex
      password: alex

  #Postgres Database
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: alex
    password: alex
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update